# Generated by Django 3.2.6 on 2021-08-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefreeshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='title',
            new_name='website',
        ),
    ]
